import type { ComponentType } from "react";
import {
  GitHubBrandIcon,
  GitLabBrandIcon,
  CodebergBrandIcon,
  GitBrandIcon,
} from "../components/BrandIcons";
import {
  GitFork,
  Globe,
  Link as LinkIcon,
  BookOpen,
  Mail,
  Home,
  GraduationCap,
  Video,
  Phone,
  MapPin,
  MessageCircle,
  Send,
  Inbox,
  Wifi,
  Users,
  User,
  Heart,
  Star,
  ThumbsUp,
  FileText,
  File,
  Folder,
  Archive,
  Navigation,
  Compass,
  Camera,
  Image,
  Music,
  Mic,
  Code,
  Terminal,
  Cpu,
  Database,
  Server,
  Cloud,
  School,
  Building,
  Building2,
  Landmark,
  Award,
  ShoppingCart,
  CreditCard,
  Wallet,
  Gift,
  Calendar,
  Clock,
  Bell,
  Flag,
  Shield,
  Lock,
  Settings,
  Info,
  HelpCircle,
  Zap,
  Lightbulb,
  Printer,
  Wrench,
  Package,
  Newspaper,
  Rss,
  Share2,
  QrCode,
  Library,
  Notebook,
  ClipboardList,
  Trophy,
  Target,
  Rocket,
  Coffee,
} from "lucide-react";

/** `footer_links[].icon_url` values starting with this prefix pick a bundled
 * icon instead of an admin-uploaded image — no upload needed for common
 * links like GitHub (lucide-react ships no brand icons, so `GitFork` stands
 * in for source-code/repository links). */
export const PRESET_ICON_PREFIX = "icon:";

/** Every icon an admin can pick for a footer link, keyed by a stable name
 * (also used as the search term in the picker dropdown). Mixes lucide-react
 * icons with a few hand-embedded brand marks (lucide ships none). */
export const FOOTER_ICON_PRESETS: Record<string, ComponentType<{ size?: number }>> = {
  github: GitHubBrandIcon,
  gitlab: GitLabBrandIcon,
  codeberg: CodebergBrandIcon,
  git: GitBrandIcon,
  repository: GitFork,
  globe: Globe,
  link: LinkIcon,
  docs: BookOpen,
  mail: Mail,
  home: Home,
  university: GraduationCap,
  video: Video,
  phone: Phone,
  location: MapPin,
  message: MessageCircle,
  send: Send,
  inbox: Inbox,
  wifi: Wifi,
  users: Users,
  user: User,
  heart: Heart,
  star: Star,
  like: ThumbsUp,
  document: FileText,
  file: File,
  folder: Folder,
  archive: Archive,
  navigation: Navigation,
  compass: Compass,
  camera: Camera,
  image: Image,
  music: Music,
  microphone: Mic,
  code: Code,
  terminal: Terminal,
  cpu: Cpu,
  database: Database,
  server: Server,
  cloud: Cloud,
  school: School,
  building: Building,
  campus: Building2,
  landmark: Landmark,
  award: Award,
  shop: ShoppingCart,
  payment: CreditCard,
  wallet: Wallet,
  gift: Gift,
  calendar: Calendar,
  clock: Clock,
  bell: Bell,
  flag: Flag,
  shield: Shield,
  lock: Lock,
  settings: Settings,
  info: Info,
  help: HelpCircle,
  bolt: Zap,
  idea: Lightbulb,
  printer: Printer,
  tools: Wrench,
  package: Package,
  news: Newspaper,
  feed: Rss,
  share: Share2,
  qrcode: QrCode,
  library: Library,
  notebook: Notebook,
  checklist: ClipboardList,
  trophy: Trophy,
  target: Target,
  rocket: Rocket,
  coffee: Coffee,
};

export const footerPresetIconFor = (
  iconUrl: string,
): ComponentType<{ size?: number }> | null =>
  iconUrl.startsWith(PRESET_ICON_PREFIX)
    ? (FOOTER_ICON_PRESETS[iconUrl.slice(PRESET_ICON_PREFIX.length)] ?? null)
    : null;
